name: 'PR Protector'
description: 'A lightweight approach for protecting your PR from introducing unintended vulnerabilities'
author: 'Sonatype'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'shield'
  color: 'blue'

# Define your inputs here.
inputs:
  iq-username:
    description: 'The username to authenticate with Lifecycle (IQ Server)'
    required: true
  iq-password:
    description: 'The password to authenticate with Lifecycle (IQ Server)'
    required: true
  iq-app-id:
    description: 'The Lifecycle (IQ Server) application'
    required: true

runs:
  using: 'composite'
  steps:
    - name: 'Checkout the PR branch'
      if : ${{ github.head_ref != '' }}
      uses: actions/checkout@v4
      with:
        ref: ${{ github.head_ref }}
        path: source-temp

    - name: 'Detect maven components on the PR branch'
      if : ${{ github.head_ref != '' }}
      shell: bash
      run: |
        cd source-temp
        mvn -B dependency:tree -DoutputType=dot > source-dependency-tree.txt 2>&1

    - name: 'Checkout the target branch'
      if : ${{ github.base_ref != '' }}
      uses: actions/checkout@v4
      with:
        ref: ${{ github.base_ref }}
        path: target-temp

    - name: 'Detect maven components on the target branch'
      if : ${{ github.base_ref != '' }}
      shell: bash
      run: |
        cd target-temp
        mvn -B dependency:tree -DoutputType=dot > target-dependency-tree.txt 2>&1

    - name: 'Detect PR introduced vulnerabilities'
      uses: eduard-tita/hackaton@main
      env:
        USERNAME: ${{ inputs.iq-username }}
        PASSWORD: ${{ inputs.iq-password }}
        APP_ID: ${{ inputs.iq-app-id }}
        GITHUB_TOKEN: ${{ github.token }}

    - name: 'Upload artifacts (for troubleshooting only)'
      uses: actions/upload-artifact@v4
      with:
        name: dependency-trees
        path: |
          source-temp/*-dependency-tree.txt
          target-temp/*-dependency-tree.txt
